Native json
Flow-Launcher/Flow.Launcher.JsonRPC.Python pull request #15
Opened 2022-04-20 17:49 UTC by mrmetrix4

POC that flow can work with the native json lib.
BTW: Did some research, we can add `separators=(",", ":")` to dumps if we want it to mimic demjson behavior.

2022-04-26 14:00 UTC, Zeroto521 requested changes
`sys.argv` is a port for Flow Launcher. So the inputting is a standard JSON.

2022-04-26 14:21 UTC, mrmetrix4 commented on flowlauncher/FlowLauncher.py
>          if len(sys.argv) > 1:  # from input to get jsonrpc
debug is currently not working TBH.

2022-04-26 14:26 UTC, mrmetrix4 commented on flowlauncher/FlowLauncher.py
Fixed.

2022-04-26 14:26 UTC, mrmetrix4 commented on requirements.txt
> -demjson
Fixed.

2022-04-26 14:28 UTC, mrmetrix4 commented on flowlauncher/FlowLauncher.py
>          if len(sys.argv) > 1:  # from input to get jsonrpc
All other things are fixed.

2022-04-27 12:46 UTC, Zeroto521 approved these changes
Thanks for committing to this feature.

If there is no more new problem, I will merge this into the master branch.

2022-04-28 12:41 UTC, merged